/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestGson;

public class App {
    String path = "recentquotes.json";

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
