/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestGson;

import com.google.gson.stream.JsonReader;

import java.io.FileReader;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        String path = "src/main/resources/recentquotes.json";
        ParseJson parser = new ParseJson(path);

        parser.createResponseList();

        parser.printRandom();
    }

}
